<?php

namespace App\Http\Controllers\Voyager;

use App\Helpers\Help;
use App\Page;
use Illuminate\Http\Request;
use TCG\Voyager\Http\Controllers\VoyagerBaseController as BaseVoyagerBaseController;
use TCG\Voyager\Models\Menu;
use TCG\Voyager\Models\MenuItem;

class PagesController extends BaseVoyagerBaseController
{
    public function store(Request $request)
    {
        if(Page::where('slug', $request->slug)->first()) return back()->withErrors('Strona o takim linku już istnieje');
        $to_return = parent::store($request); // TODO: Change the autogenerated stub
        $page = Page::orderBy('created_at', 'desc')->first();
        if($page->title == $request->title){
            $menu = Menu::where('name', 'Home')->first();
            if($menu){
                if($page->parent_id){
                    $parent = $page->parent;
                    $item = $menu->items()->whereRaw('LOWER(`title`) LIKE ? ',[trim(strtolower($parent->title)).'%'])->first();
                    $order = MenuItem::where('parent_id', $item->id)->count() + 1;
                    if($item && $item->parameters){
                        if(!is_object($item->parameters)){
                            $tmp = json_decode($item->parameters);
                        }
                        if(isset($tmp) && is_object($tmp)){
                            $slug_parent = $tmp->slug;
                        }
                    }
                    if(isset($slug_parent)){
                        $slug = ($slug_parent)? $slug_parent : '';
                        $slug = $slug.'/'.$page->slug;
                        $paramters = json_encode([
                            'slug' => $slug
                        ]);
                    }else{
                        $paramters = json_encode(['slug' => $page->slug]);
                    }
                }else{
                    $order = $menu->items()->where('parent_id', null)->count() + 1;
                    $paramters = json_encode(['slug' => $page->slug]);
                }

                $menu->items()->create([
                    'title' => $page->title,
                    'url' => '',
                    'target' => '_self',
                    'parent_id' => (isset($item) && $item)? $item->id : null,
                    'order' => $order,
                    'route' => 'page',
                    'parameters' => $paramters
                ]);
               /* $menu->items()->create([
                    ''
                ])*/
            }
        }
        return $to_return;
    }

}
